name: "AutoRelease Test"

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the release/0.7 branch
  push:
    branches: [ release ]


env:
  GODOT_VERSION: 4.2.1
  EXPORT_NAME: CaccaDog
  PROJECT_PATH: Godot

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Grab Version
        run: echo "PROJECT_VERSION=$(head -1 $PROJECT_PATH/VERSION.txt)" >> $GITHUB_ENV
    
      - name: Show Version
        run: echo "${{ env.PROJECT_VERSION }}"
      
      - name: GitHub Tag Exists
        uses: mukunku/tag-exists-action@v1.0.0
        id: check-tag
        with: 
          tag: "v${{ env.PROJECT_VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        
      - run: echo "Tag exists!"; exit 1;
        if: steps.check-tag.outputs.exists == 'true'
      
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows
          path: build/windows
